config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins

  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type #,optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  #layout "adm"

  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.collect { |m| [m.description, m.id]}
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on Rails [Cookies]}"
    session[:curso] = "Curso de Ruby on Rails [Session]}"
    @meu_nome = params[:nome]
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def locale
        I18n.locale == :en ? "Estados Unidos" : "Português do Brasil"
    end

    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end

    def ambiente_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else
            "Teste"
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
    <%#= image_tag coin.url_image, width: 25, height: 25 %>
  </div>

  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, {include_blank: 'Select...'}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t('edit.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.show'), @coin %> |
<%= link_to t('links.back'), coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Coin.model_name.human(count: @coins.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%=@coins.human_attribute_name(:description)%></th>
      <th><%=@coins.human_attribute_name(:acronym)%></th>
      <th><%=@coins.human_attribute_name(:url_image)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, size: "25x25" %></td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('confirm_msg') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.coin'), new_coin_path, class:"btn btn-primary" %>

app/views/coins/new.html.erb
<h1><%= t('new.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.back'), coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= image_tag @coin.url_image, size: "25x25" %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>CABEÇALHO - adm </h1>
    <%= yield %>
    <h1>RODAPÉ - adm</h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to 'Português', root_path(locale: 'pt-BR'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'English', root_path(locale: 'en'), class:"nav-link" %>
        </li>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%=@mining_types.human_attribute_name(:description)%></th>
      <th><%=@mining_types.human_attribute_name(:acronym)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('confirm_msg') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.mining_type'), new_mining_type_path, class:"btn btn-primary" %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", coins_path, class:"btn btn-primary btn-lg", role:"button" %>
<%= link_to "#{MiningType.model_name.human}", mining_types_path, class:"btn btn-primary btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %></h1>
  <p class="lead"><%= t('welcome_msg') %></p>
  <hr class="my-4">
  <p><%= t('menu_msg') %></p>
  <p class="lead">
    <%= render "menu" %>
  </p>
</div>